In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from IPython.display import display
import time
from IPython.display import clear_output

tt_demo = pd.read_excel('./demo_tt.xlsx')
tt_demo = tt_demo.head(20)

In [2]:
tt_demo

    feature 1  feature 2  Value
0           7         10     89
1           0          8     59
2           5         10     84
3         -10          4     19
4           3          8     69
5          -1          7     58
6           7          8     76
7          -7          8     54
8           5          9     80
9           9         10     91
10         -3          9     71
11         -1          3     27
12        -10          5     34
13          2          3     28
14         -9          4     25
15         10          3     39
16          5          2     25
17         -6          4     31
18         -4          4     32
19          0          5     43

In [3]:
tt_demo.iloc[:,-1:]

    Value
0      89
1      59
2      84
3      19
4      69
5      58
6      76
7      54
8      80
9      91
10     71
11     27
12     34
13     28
14     25
15     39
16     25
17     31
18     32
19     43

In [4]:
X = tt_demo[['feature 1','feature 2']]
y = tt_demo['Value']

In [6]:
scores = []
for i in range(1,20):
    
    X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)
    
    tt_demo['in_train'] = ~tt_demo.index.isin(X_test.index)
    tt_demo['in_test'] = tt_demo.index.isin(X_test.index)
    clear_output(wait = True)
    lr = LinearRegression()
    lr.fit(X_train,y_train)
    print(f"train test has run {i} times")
    display(tt_demo.head(20).style.apply(lambda x: ["background-color: lightgreen"]*len(x) if x['in_train']==True else ["background-color: yellow"]*len(x),axis = 1))
    
    display(f"on test {i} the model had an r^2 score of: {lr.score(X_test,y_test)}")
    scores.append(lr.score(X_test,y_test))
    
    time.sleep(1)

train test has run 19 times

'on test 19 the model had an r^2 score of: 0.989137715219879'

In [4]:
scores

[0.9774554317168663,
 0.9853260359209263,
 0.9893447153871442,
 0.9644009970926888,
 0.9874005004280344,
 0.9108518719105216,
 0.9543019742472831,
 0.9836823378064451,
 0.9906685795942628,
 0.9453201582258943,
 0.9869259895305671,
 0.9840625763763147,
 0.9705323937881614,
 0.992116608737953,
 0.977223235301782,
 0.9631053093042402,
 0.9825613010798423,
 0.978229383450371,
 0.9863776419739241]